load("//UrlGet.xcodeproj/XCHammerAssets:Hammer.bzl", "export_entitlements")

export_entitlements(
    name = "ios-app-share-extension_entitlements",
    bundle_id = "Google.UrlGet.ShareExtension",
    entitlements = None,
    platform_type = "ios",
    provisioning_profile = None,
)

export_entitlements(
    name = "ios-app-strings-extension_entitlements",
    bundle_id = "Google.UrlGet.StringsExtension",
    entitlements = None,
    platform_type = "ios",
    provisioning_profile = None,
)

export_entitlements(
    name = "ios-app-siri-extension_entitlements",
    bundle_id = "Google.UrlGet.SiriExtension",
    entitlements = None,
    platform_type = "ios",
    provisioning_profile = None,
)

export_entitlements(
    name = "ios-app-ios-app_entitlements",
    bundle_id = "Google.UrlGet",
    entitlements = None,
    platform_type = "ios",
    provisioning_profile = None,
)
