language: generic
env:
  - BAZEL_BUILD=true
  - BAZEL_BUILD=false
os:
  - osx
cache:
  directories:
    - $HOME/.bazelenv
    - $HOME/Library/Caches/Bazel
    - $HOME/.bazel_pod_store
before_install:
  - sudo gem install cocoapods
osx_image: xcode10.2
script: make ci
