language: generic
env:
  - BAZEL_BUILD=true
  - BAZEL_BUILD=false
os:
  - osx
cache:
  directories:
    - $HOME/.bazelenv
before_install:
  - sudo gem install cocoapods
osx_image: xcode10
script: make ci
