load('@bazel_tools//tools/build_defs/repo:git.bzl', system_git_repository='git_repository')

git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    commit = "6f93226e29fef0ac6ba00fb5dc56389d3bd8c25f",
)

load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

apple_rules_dependencies()

http_file(
    name = "xctestrunner",
    executable = 1,
    urls = ["https://github.com/google/xctestrunner/releases/download/0.2.3/ios_test_runner.par"]
)
