load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

# Build with changes to add --standalone to test invocation. Additionally, fix
# several python build issues
http_file(
    name = "xctestrunner",
    executable = 1,
    urls = ["https://github.com/jerrymarino/xctestrunner/files/3453677/ios_test_runner.par.zip"],
)

git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    tag = "0.18.0",
)

load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

git_repository(
    name = "build_bazel_rules_swift",
    commit = "0192f16b82b2998d846c45187545e38548a6671a",
    remote = "https://github.com/bazelbuild/rules_swift.git",
)

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

apple_rules_dependencies(ignore_version_differences = True)

load(
    "@com_google_protobuf//:protobuf_deps.bzl",
    "protobuf_deps",
)

protobuf_deps()

load(
    "@build_bazel_apple_support//lib:repositories.bzl",
    "apple_support_dependencies",
)

apple_support_dependencies()

http_file(
    name = "xctestrunner",
    executable = 1,
    urls = ["https://github.com/google/xctestrunner/releases/download/0.2.6/ios_test_runner.par"],
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_pods",
    urls = ["https://github.com/pinterest/PodToBUILD/releases/download/0.25.2-d76cb615/PodToBUILD.zip"],
)

# XCHammer resources
# We currently do a binary check-in of XCHammer and need to alias the
# resources so they can be loaded
local_repository(
    name = "xchammer_resources",
    path = "tools/xchammer.app/Contents/Resources",
)
