// Copyright 2018-present, Pinterest, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.import Foundation

import TulsiGenerator
import ShellOut
import PathKit

/// Final Tagless DSL for BazelQuery formulas
/// Necessary so that we don't mess up formatting strings manually
/// Primitives
protocol BazelQueryLang {
    static func binop(left: Self, op: String, right: Self) -> Self
    static func application(name: String, params: [Self]) -> Self
    static func str(_ s: String) -> Self
    static func word(_ w: String) -> Self
}

/// Helpers
extension BazelQueryLang {
    static func deps(_ word: Self) -> Self {
        return application(name: "deps", params: [word])
    }
    
    static func kind(_ which: Self, _ expr: Self) -> Self {
        return application(name: "kind", params: [which, expr])
    }
    
    static func union(lhs: Self, rhs: Self) -> Self {
        return binop(left: lhs, op: "union", right: rhs)
    }
    
    static func set(_ params: [Self]) -> Self {
        return application(name: "set", params:params)
    }
}

/// Renderer
extension String: BazelQueryLang {
    static func binop(left: String, op: String, right: String) -> String {
        return "\(left) \(op) \(right)"
    }
    
    static func application(name: String, params: [String]) -> String {
        return "\(name)(\(params.joined(separator: ",")))"
    }
    
    static func str(_ s: String) -> String {
        return "\"\(s)\""
    }
    
    static func word(_ w: String) -> String {
        return "\(w)"
    }
}

enum BazelQueryer {
    /// Query bazel for any generated files the project depends on
    /// It include rules of tag 'xchammer'. The user can include arbitrary
    /// Note: This is generally used for Xcode's build system.
    /// Any files in the project generated by Bazel are populated during the
    /// Bazel build
    static func genFileQuery(targets: [BuildLabel], bazelPath: Path, workspaceRoot: Path) throws -> [BuildLabel] {
        let genfileProfiler = XCHammerProfiler("query_genfiles")
        defer {
            genfileProfiler.logEnd(true)
        }

        let queryParts: [String] = targets.reduce([]) {
            accum, target -> [String] in
            return accum + [
                String.application(name: "attr", params: [.str("tags"),
                        .str("xchammer"), .deps(.word(target.description))]),
            ]
        }
        let query = queryParts.reduce(.set([]), String.union)

        let command: String = ([
            bazelPath.string,
            "query",
            "--output=label_kind",
            "'\(query)'"
        ]).joined(separator: " ")
        let output = try ShellOut.shellOut(to: [command], at: workspaceRoot.string)
        
        return output.split(separator: "\n")
            .map{ $0.split(separator: " ").last! }
            .map{ BuildLabel(String($0)) }
    }
}

extension Array where Element == String {
    /// Concat the start to the beginning of the first element, and the end to the end of the last element
    /// Ex: ["a", "b", "c"].surroundInside("(", ")") => ["(a", "b", "c)"]
    func surroundInside(start: String, end: String) -> Array {
        return ([start + self[startIndex]] as [String]) +
            Array(dropFirst().dropLast()) +
            [self[endIndex-1] + end]
    }
}
