name: Main workflow 

on: [pull_request]

# **THE FOLLOWING SEGMENT SHOULD BE KEPT IDENTICAL BETWEEN `CI.YML` UNTIL A BETTER IDEA COMES UP**
# Consider finding a way to unify this with `ci.yml`. Per the github actions
# docs, I'm not sure about how to do that.
# Github actions seems to want to run the jobs 2x when there is multiple `on` keywords
# e.g.  on: [pull_request, push]
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
jobs:
  # Note: currently we share the Bazel cache to speed up parallel jobs.
  # Ideally, we can update these jobs to use the a release artifact of XCHammer
  # once https://github.com/pinterest/xchammer/pull/258 is landed.
  # Ideally, it also can create a github release of XCHammer as well.
  make_build:
    name: make_build
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: make_build
      run: make build

  make_test:
    name: make_test
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: make_test
      run: make test

  run_perf_ci:
    name: run_perf_ci
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    # Consider pulling this out to use the WORKSPACE rule
    - name: pod_cache
      uses: actions/cache@v2
      env:
        cache-name: pod-cache
      with:
        path: ~/.bazel_pod_store
        key: ${{ runner.os }}-pods-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-pods-${{ env.cache-name }}-

    - name: cocoapods
      run: sudo gem install cocoapods 

    - name: run_perf_ci
      run: make run_perf_ci

  run_swift:
    name: run_swift
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: run_swift
      run: make run_swift

  run_force_bazel:
    name: run_force_bazel
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: run_force_bazel
      run: make run_force_bazel

  workspace:
    name: workspace
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: workspace
      run: make workspace

  workspace_v2:
    name: workspace_v2
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: workspace_v2
      run: make workspace_v2

  # This uploads `xchammer.zip` as an artifact to github actions
  # For issues mentioned here
  # https://github.com/actions/upload-artifact/issues/50
  # The Github URL can't be used with Bazel directly in an `http_archive`
  # At the time of writing the only way to consume it is to:
  # - get the release URL with the github actions API which is valid for 1 minute
  # - pull the zip from that URL and re-host it: or somehow use it locally.
  # - it'd probably be possible to impalement as a github actions repository
  #   and that's a lot of unwarranted complexity to integrate XCHammer.
  #
  # See README.md of how to use the artifact with Bazel
  make_release:
    name: make_release
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: bazel_cache_release
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache-release
        with:
          path: ~/Library/Caches/Bazel
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: make_release
        run: |
            make release
            # Set the BAZEL_BIN env var to the realpath
            # Note: actions/upload-artifact@v2 at time of writing is falling
            # apart when we give it a symlink base path
            echo ::set-env name=BAZEL_BIN::$(readlink bazel-bin)
      - uses: actions/upload-artifact@v2
        with:	
          name: xchammer
          path: ${{ env.BAZEL_BIN }}/xchammer_dist_repo.zip
