name: Main workflow

on: [pull_request]

jobs:
  Lint:
    name: Run Unit and Integration Tests (macOS)
    runs-on: macOS-latest
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v1
    - name: Setup dependencies
      run: sudo gem install cocoapods
    - name: Run Tests (test)
      run: make test
    - name: Run Swift Tests
      run: make run_swift
    - name: Run Goldmaster Tests
      run: make goldmaster
    - name: Run Perf Tests
      run: make run_perf_ci
