name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Note: currently we share the Bazel cache to speed up parallel jobs.
  # Ideally, we can update these jobs to use the a release artifact of XCHammer
  # once https://github.com/pinterest/xchammer/pull/258 is landed.
  # Ideally, it also can create a github release of XCHammer as well.
  make_build:
    name: make_build
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: make_build
      run: make build

  make_test:
    name: make_test
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: make_test
      run: make test

  run_perf_ci:
    name: run_perf_ci
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    # Consider pulling this out to use the WORKSPACE rule
    - name: pod_cache
      uses: actions/cache@v2
      env:
        cache-name: pod-cache
      with:
        path: ~/.bazel_pod_store
        key: ${{ runner.os }}-pods-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-pods-${{ env.cache-name }}-

    - name: cocoapods
      run: sudo gem install cocoapods 

    - name: run_perf_ci
      run: make run_perf_ci

  run_swift:
    name: run_swift
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: run_swift
      run: make run_swift

  run_force_bazel:
    name: run_force_bazel
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: run_force_bazel
      run: make run_force_bazel

  workspace:
    name: workspace
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: workspace
      run: make workspace

  workspace_v2:
    name: workspace_v2
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: workspace_v2
      run: make workspace_v2
