name: Main workflow 

# Note: github actions seems to want to run the actions 2x is this intentional
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
on: [pull_request, push]

jobs:
  make_build:
    name: make_build
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: make_build
      run: make build

  make_test:
    name: make_test
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: make_test
      run: make test

  run_perf_ci:
    name: run_perf_ci
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    # Consider pulling this out to use the WORKSPACE rule
    - name: pod_cache
      uses: actions/cache@v2
      env:
        cache-name: pod-cache
      with:
        path: ~/.bazel_pod_store
        key: ${{ runner.os }}-pods-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-pods-${{ env.cache-name }}-

    - name: cocoapods
      run: sudo gem install cocoapods 

    - name: run_perf_ci
      run: make run_perf_ci

  run_swift:
    name: run_swift
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: run_swift
      run: make run_swift

  run_force_bazel:
    name: run_force_bazel
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: run_force_bazel
      run: make run_force_bazel

  # I'm not sure if this is used anymore. It'd be nice if there was a better way
  # to handle this
  goldmaster:
    name: goldmaster
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-


    - name: goldmaster
      run: make goldmaster

  workspace:
    name: workspace
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: workspace
      run: make workspace

  workspace_v2:
    name: workspace_v2
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: bazel_cache
      uses: actions/cache@v2
      env:
        cache-name: bazel-cache
      with:
        path: ~/Library/Caches/Bazel
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: workspace_v2
      run: make workspace_v2

