name: Main workflow 

on: [push, pull_request]

jobs:
  Lint:
    name: Run Unit and Integration Tests (macOS)
    runs-on: macOS-latest
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v1
    - name: Setup dependencies 
      run: sudo gem install cocoapods 
    - name: Run Tests
      run: BAZEL_BUILD=${{ matrix.bazel_enabled }} make ci
    strategy:
      matrix:
        bazel_enabled: [true, false]
